APPLICATION_NAME = AppListSample
AppListSample_FILES = application.m
AppListSample_FRAMEWORKS = UIKit CoreGraphics
AppListSample_PRIVATE_FRAMEWORKS = Preferences
AppListSample_CFLAGS = -I../
AppListSample_LDFLAGS = -L../$(FW_OBJ_DIR)
AppListSample_LIBRARIES = applist

TARGET_IPHONEOS_DEPLOYMENT_VERSION = 3.0

include framework/makefiles/common.mk
include framework/makefiles/application.mk
